# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: article.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='article.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\rarticle.proto\"$\n\x11\x41\x64\x64\x41rticleRequest\x12\x0f\n\x07\x61rticle\x18\x01 \x01(\t\"P\n\x0f\x41\x64\x64\x41rticleReply\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x0b\n\x03msg\x18\x02 \x01(\t\x12\"\n\x04\x64\x61ta\x18\x03 \x01(\x0b\x32\x14.AddArticleReplyData\"!\n\x13\x41\x64\x64\x41rticleReplyData\x12\n\n\x02id\x18\x01 \x01(\x03\"\"\n\x14SelectArticleRequest\x12\n\n\x02id\x18\x01 \x01(\x03\"V\n\x12SelectArticleReply\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x0b\n\x03msg\x18\x02 \x01(\t\x12%\n\x04\x64\x61ta\x18\x03 \x01(\x0b\x32\x17.SelectArticleReplyData\"5\n\x16SelectArticleReplyData\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x0f\n\x07\x61rticle\x18\x02 \x01(\t\"3\n\x14UpdateArticleRequest\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x0f\n\x07\x61rticle\x18\x02 \x01(\t\"V\n\x12UpdateArticleReply\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x0b\n\x03msg\x18\x02 \x01(\t\x12%\n\x04\x64\x61ta\x18\x03 \x01(\x0b\x32\x17.UpdateArticleReplyData\"$\n\x16UpdateArticleReplyData\x12\n\n\x02id\x18\x01 \x01(\x03\x32\xc4\x01\n\x0e\x41rticleService\x12\x34\n\nAddArticle\x12\x12.AddArticleRequest\x1a\x10.AddArticleReply\"\x00\x12=\n\rSelectArticle\x12\x15.SelectArticleRequest\x1a\x13.SelectArticleReply\"\x00\x12=\n\rUpdateArticle\x12\x15.UpdateArticleRequest\x1a\x13.UpdateArticleReply\"\x00\x62\x06proto3')
)




_ADDARTICLEREQUEST = _descriptor.Descriptor(
  name='AddArticleRequest',
  full_name='AddArticleRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='article', full_name='AddArticleRequest.article', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=17,
  serialized_end=53,
)


_ADDARTICLEREPLY = _descriptor.Descriptor(
  name='AddArticleReply',
  full_name='AddArticleReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='AddArticleReply.code', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='msg', full_name='AddArticleReply.msg', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='AddArticleReply.data', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=55,
  serialized_end=135,
)


_ADDARTICLEREPLYDATA = _descriptor.Descriptor(
  name='AddArticleReplyData',
  full_name='AddArticleReplyData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='AddArticleReplyData.id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=137,
  serialized_end=170,
)


_SELECTARTICLEREQUEST = _descriptor.Descriptor(
  name='SelectArticleRequest',
  full_name='SelectArticleRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='SelectArticleRequest.id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=172,
  serialized_end=206,
)


_SELECTARTICLEREPLY = _descriptor.Descriptor(
  name='SelectArticleReply',
  full_name='SelectArticleReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='SelectArticleReply.code', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='msg', full_name='SelectArticleReply.msg', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='SelectArticleReply.data', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=208,
  serialized_end=294,
)


_SELECTARTICLEREPLYDATA = _descriptor.Descriptor(
  name='SelectArticleReplyData',
  full_name='SelectArticleReplyData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='SelectArticleReplyData.id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='article', full_name='SelectArticleReplyData.article', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=296,
  serialized_end=349,
)


_UPDATEARTICLEREQUEST = _descriptor.Descriptor(
  name='UpdateArticleRequest',
  full_name='UpdateArticleRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='UpdateArticleRequest.id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='article', full_name='UpdateArticleRequest.article', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=351,
  serialized_end=402,
)


_UPDATEARTICLEREPLY = _descriptor.Descriptor(
  name='UpdateArticleReply',
  full_name='UpdateArticleReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='UpdateArticleReply.code', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='msg', full_name='UpdateArticleReply.msg', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='UpdateArticleReply.data', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=404,
  serialized_end=490,
)


_UPDATEARTICLEREPLYDATA = _descriptor.Descriptor(
  name='UpdateArticleReplyData',
  full_name='UpdateArticleReplyData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='UpdateArticleReplyData.id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=492,
  serialized_end=528,
)

_ADDARTICLEREPLY.fields_by_name['data'].message_type = _ADDARTICLEREPLYDATA
_SELECTARTICLEREPLY.fields_by_name['data'].message_type = _SELECTARTICLEREPLYDATA
_UPDATEARTICLEREPLY.fields_by_name['data'].message_type = _UPDATEARTICLEREPLYDATA
DESCRIPTOR.message_types_by_name['AddArticleRequest'] = _ADDARTICLEREQUEST
DESCRIPTOR.message_types_by_name['AddArticleReply'] = _ADDARTICLEREPLY
DESCRIPTOR.message_types_by_name['AddArticleReplyData'] = _ADDARTICLEREPLYDATA
DESCRIPTOR.message_types_by_name['SelectArticleRequest'] = _SELECTARTICLEREQUEST
DESCRIPTOR.message_types_by_name['SelectArticleReply'] = _SELECTARTICLEREPLY
DESCRIPTOR.message_types_by_name['SelectArticleReplyData'] = _SELECTARTICLEREPLYDATA
DESCRIPTOR.message_types_by_name['UpdateArticleRequest'] = _UPDATEARTICLEREQUEST
DESCRIPTOR.message_types_by_name['UpdateArticleReply'] = _UPDATEARTICLEREPLY
DESCRIPTOR.message_types_by_name['UpdateArticleReplyData'] = _UPDATEARTICLEREPLYDATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AddArticleRequest = _reflection.GeneratedProtocolMessageType('AddArticleRequest', (_message.Message,), {
  'DESCRIPTOR' : _ADDARTICLEREQUEST,
  '__module__' : 'article_pb2'
  # @@protoc_insertion_point(class_scope:AddArticleRequest)
  })
_sym_db.RegisterMessage(AddArticleRequest)

AddArticleReply = _reflection.GeneratedProtocolMessageType('AddArticleReply', (_message.Message,), {
  'DESCRIPTOR' : _ADDARTICLEREPLY,
  '__module__' : 'article_pb2'
  # @@protoc_insertion_point(class_scope:AddArticleReply)
  })
_sym_db.RegisterMessage(AddArticleReply)

AddArticleReplyData = _reflection.GeneratedProtocolMessageType('AddArticleReplyData', (_message.Message,), {
  'DESCRIPTOR' : _ADDARTICLEREPLYDATA,
  '__module__' : 'article_pb2'
  # @@protoc_insertion_point(class_scope:AddArticleReplyData)
  })
_sym_db.RegisterMessage(AddArticleReplyData)

SelectArticleRequest = _reflection.GeneratedProtocolMessageType('SelectArticleRequest', (_message.Message,), {
  'DESCRIPTOR' : _SELECTARTICLEREQUEST,
  '__module__' : 'article_pb2'
  # @@protoc_insertion_point(class_scope:SelectArticleRequest)
  })
_sym_db.RegisterMessage(SelectArticleRequest)

SelectArticleReply = _reflection.GeneratedProtocolMessageType('SelectArticleReply', (_message.Message,), {
  'DESCRIPTOR' : _SELECTARTICLEREPLY,
  '__module__' : 'article_pb2'
  # @@protoc_insertion_point(class_scope:SelectArticleReply)
  })
_sym_db.RegisterMessage(SelectArticleReply)

SelectArticleReplyData = _reflection.GeneratedProtocolMessageType('SelectArticleReplyData', (_message.Message,), {
  'DESCRIPTOR' : _SELECTARTICLEREPLYDATA,
  '__module__' : 'article_pb2'
  # @@protoc_insertion_point(class_scope:SelectArticleReplyData)
  })
_sym_db.RegisterMessage(SelectArticleReplyData)

UpdateArticleRequest = _reflection.GeneratedProtocolMessageType('UpdateArticleRequest', (_message.Message,), {
  'DESCRIPTOR' : _UPDATEARTICLEREQUEST,
  '__module__' : 'article_pb2'
  # @@protoc_insertion_point(class_scope:UpdateArticleRequest)
  })
_sym_db.RegisterMessage(UpdateArticleRequest)

UpdateArticleReply = _reflection.GeneratedProtocolMessageType('UpdateArticleReply', (_message.Message,), {
  'DESCRIPTOR' : _UPDATEARTICLEREPLY,
  '__module__' : 'article_pb2'
  # @@protoc_insertion_point(class_scope:UpdateArticleReply)
  })
_sym_db.RegisterMessage(UpdateArticleReply)

UpdateArticleReplyData = _reflection.GeneratedProtocolMessageType('UpdateArticleReplyData', (_message.Message,), {
  'DESCRIPTOR' : _UPDATEARTICLEREPLYDATA,
  '__module__' : 'article_pb2'
  # @@protoc_insertion_point(class_scope:UpdateArticleReplyData)
  })
_sym_db.RegisterMessage(UpdateArticleReplyData)



_ARTICLESERVICE = _descriptor.ServiceDescriptor(
  name='ArticleService',
  full_name='ArticleService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=531,
  serialized_end=727,
  methods=[
  _descriptor.MethodDescriptor(
    name='AddArticle',
    full_name='ArticleService.AddArticle',
    index=0,
    containing_service=None,
    input_type=_ADDARTICLEREQUEST,
    output_type=_ADDARTICLEREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SelectArticle',
    full_name='ArticleService.SelectArticle',
    index=1,
    containing_service=None,
    input_type=_SELECTARTICLEREQUEST,
    output_type=_SELECTARTICLEREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='UpdateArticle',
    full_name='ArticleService.UpdateArticle',
    index=2,
    containing_service=None,
    input_type=_UPDATEARTICLEREQUEST,
    output_type=_UPDATEARTICLEREPLY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_ARTICLESERVICE)

DESCRIPTOR.services_by_name['ArticleService'] = _ARTICLESERVICE

# @@protoc_insertion_point(module_scope)
